apply from: gradle.ext.sharedModulesConstants
apply plugin: 'com.android.built-in-kotlin'
apply plugin: 'com.android.library'

android {
    namespace 'com.github.vkay94.dtpv'
    compileSdkVersion project.properties.compileSdkVersion
    buildToolsVersion project.properties.buildToolsVersion

    defaultConfig {
        minSdkVersion project.properties.minSdkVersion
        targetSdkVersion project.properties.targetSdkVersion
        versionCode 40001
        versionName '1.0.4'

        vectorDrawables.useSupportLibrary = true

        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_24
        targetCompatibility JavaVersion.VERSION_24
    }

    // kotlinOptions {
    //     jvmTarget = JavaVersion.VERSION_24
    // }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:' + kotlinVersion
    implementation 'androidx.appcompat:appcompat:' + appCompatXVersion
    implementation 'androidx.core:core-ktx:' + kotlinCoreXVersion
    implementation 'androidx.constraintlayout:constraintlayout:' + constraintLayoutXVersion

    implementation project(':exoplayer-library-core')
    implementation project(':exoplayer-library-ui')
}
